[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sola_table = "GdFRCmL2NYrB42712pU45t8C9Uj1nKLYKzg8NjkrsPoK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
