[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sola_table = "8pWTbsckvHvvRN71PZ4rV2y3kexmdgRgoxgPbWYRVxsi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
